apiVersion: v1
kind: Service
metadata:
  name: docker-kubernetes-api-service
  labels:
    app: docker-kubernetes-api
spec:
  selector:
    app: docker-kubernetes-api
  ports:  
    - protocol: TCP
      port: 3000
      targetPort: 3000  
  type: NodePort
